name: Node.js Package

on:
  push:
    branches:
      - main
    paths: 
      - '**.scss'
  pull_request:
    branches: 
      - main

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: install
        run: yarn install --immutable
      - name: build
        run: yarn run build
      - name: publish
        run: cd dist && yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
